packages:
  - apps/*
  - libs/*

hoist: true

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@sentry/cli'
  - esbuild
  - supabase
  - workerd

shamefullyHoist: true
